version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: flight_alerts
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://dev:dev@db:5432/flight_alerts
      JWT_SECRET: supersecret
    depends_on:
      - db
    command: yarn start:prod

volumes:
  db-data:
